# Copyright, licenses, and data as property?

iframe / video here

transcript below:

Selfie monkey
UK copyright talks about the author of a work being the person that creates the copyright work: the person that holds the pen or paintbrush the musician strumming the guitar.  If the creator is employed or commissioned to produce the work their contract may say something different.  Copyright applies to written text based works, images, music, film and various other media.  It arises as soon as the content is create and does not require any registration, or expression of the right.  It is just exists.

Copyright applies equally in the physical and digital world and typical lasts for 70 years after the death of the author.  Copyright in a journal article is the same in the print and the e version.  Webpages and content found online then is subject to the usual copyright rules.  It requires no registration and it doesn't matter if something has the copyright symbol on it or- it is copyright protected.  If it has copyright then, someone owns it.  If someone owns copyright, that gives them the right to control who has access to it as well as if and how they can use it.   Just because something is online and open for access, it does not necessarily mean that it is free to be used.  Public domain in the openly available, in the 'out there' sense does not mean it is Public Domain, that is free from any rights. 

Copyright does allow some uses without the permission or consent of the author or owner.  What this means is that although the owner can control who accesses and uses their work, the public can still use it in certain limited situations.  These permitted acts include non-commercial research, and criticism and review.  More details on these exceptions in a research context are provided in the articles complementing this section.

Some of you may have heard of a photographer name David Slater who spent some time in the jungles of Indonesia.  He found a troupe of Crested Black Macaques and started taking pictures.  Such is their nature that they were curious and started to explore the equipment and ended up taking lots and lots of images.  

(insert Monkey selfie image & reference)

I'm sure you'll agree that the photo is fantastic and David thought so to.  When he got home began emailing publishers and newspapers and eventually in was published in the UK press- that's when the trouble started.  The image was picked up by other blogs and newspapers and eventually by Wikipedia who used it on their definition of the species , .  (Interestingly Wikipedia also now has a page on the dispute itself .)  David complained claiming his copyright and licensing fees over the image.

Is he right?

Who owns the copyright? The photographer or the macaque?

These are questions that have rumbled on since 2011 when David first released the image and subsequently when Wikipedia used the image.  They found themselves at the heart of a public debate on to mainstream media when PETA sued David on behalf of the Macaque claiming the copyright on their behalf.  Even Mock the Week the week got in on the action .

While the copyright debate continues to puzzle the season Intellectual Property professionals and international media alike , David himself says the financial and personal cost to him has been huge.  Speaking in July 2017  David was unable to represent himself in the PETA case and is struggling financially, despite the image being internationally famous.  Regardless of the copyright aspect, we need to be aware that our actions can impact on the livelihood of individuals and their dependents.

What this all means then that copyright in the digital world is a complex but important part of research literacy.  Researchers and professionals should factor in copyright as important element when considering what you content might use in a research context.  We can see that copyright is not the only or most important consideration, despite what I might think.  It should be balanced with other components of the research activity.

We'd now like to you go through a couple of exercises looking at copyright in the digital world.  Look back at the Facebook terms think about who owns data you post on Facebook?  What permission does Facebook have to use your content?  Your pictures?  Were you aware of this?  Following that we'll get you to look at copyright licences and consider how you might license your content, if you were a copyright owner.  We'll also get you to explore the nuance of the Monkey Selfie in some more detail.
